spring:
  data:
    mongodb:
      port: 27017
      host: ${base-local-host}
      username: prod
      password: LuBeSxG73CtAJhPD
      database: material_db
      authentication-database: admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
