keycloak-issuer-uri: http://keycloak:8080/auth/realms/e-shop

spring:
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: prod
    password: 3kWr7WvWBpsJVztS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer-uri}

graphql:
  servlet:
    exception-handlers-enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
