route-prefix: /e-shop/api/v1/
path-regex: /(?<path>.*)
rewrited-path-regex: /$\{path}
keycloak-token-openid-uri: http://keycloak:8080/auth/realms/e-shop/protocol/openid-connect/

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak-token-openid-uri}token
            authorization-uri: ${keycloak-token-openid-uri}auth
            userinfo-uri: ${keycloak-token-openid-uri}userinfo
            user-name-attribute: preferred_username
        registration:
          e-shop:
            provider: keycloak
            client-id: e-shop
            scope: openid
            client-secret: b8f179fb-dbb9-4181-98fd-b0bdd2390e20
            authorization-grant-type: password
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog
          uri: lb://catalog/
          predicates:
            - Path=${route-prefix}catalog/**
          filters:
            - RewritePath=${route-prefix}catalog${path-regex}, ${rewrited-path-regex}
            - RemoveRequestHeader=Cookie
            - name: CircuitBreaker
              args:
                name: defaultcircuitbreaker
                fallbackUri: forward:${route-prefix}fallback
        - id: discount
          uri: lb://discount/
          predicates:
            - Path=${route-prefix}discount/**
          filters:
            - RewritePath=${route-prefix}discount${path-regex}, ${rewrited-path-regex}
            - RemoveRequestHeader=Cookie
            - name: CircuitBreaker
              args:
                name: defaultcircuitbreaker
                fallbackUri: forward:${route-prefix}fallback
        - id: basket
          uri: lb://basket/
          predicates:
            - Path=${route-prefix}basket/**
          filters:
            - RewritePath=${route-prefix}basket${path-regex}, ${rewrited-path-regex}
            - RemoveRequestHeader=Cookie
            - name: CircuitBreaker
              args:
                name: defaultcircuitbreaker
                fallbackUri: forward:${route-prefix}fallback
